title = "InfluxData Documentation"
baseurl = "https://docs.influxdata.com"

languageCode = "en-us"

[blackfriday]
  plainIdAnchors = true


SectionPagesMenu = "products"
[[menu.products]]
  name = "Telegraf"
  identifier = "telegraf"
  weight = 2
  url = "/telegraf/"
[[menu.products]]
  name = "InfluxDB"
  identifier = "influxdb"
  weight = 1
  url = "/influxdb/"
[[menu.products]]
  name = "Kapacitor"
  identifier = "kapacitor"
  weight = 3
  url = "/kapacitor/"
[[menu.products]]
  name = "Chronograf"
  identifier = "chronograf"
  weight = 4
  url = "/chronograf/"
[[menu.products]]
  name = "Hosted"
  identifier = "hosted"
  weight = 5
  url = "/hosted/"


[[menu.influxdb]]
  name = "Introduction"
  identifier = "introduction"
  weight = 1
  url = "/influxdb/introduction/"
[[menu.influxdb]]
  name = "Guides"
  identifier = "guides"
  weight = 2
  url = "/influxdb/guides/"
[[menu.influxdb]]
  name = "Concepts"
  identifier = "concepts"
  weight = 3
  url = "/influxdb/concepts"
[[menu.influxdb]]
  name = "Troubleshooting"
  identifier = "troubleshooting"
  weight = 4
  url = "/influxdb/troubleshooting"
[[menu.influxdb]]
  name = "Write Protocols and Plugins"
  identifier = "write_protocols"
  weight = 5
  url = "/influxdb/write_protocols"
[[menu.influxdb]]
  name = "Query Language"
  identifier = "query_language"
  weight = 5
  url = "/influxdb/query_language"
[[menu.influxdb]]
  name = "Client Libraries"
  identifier = "clients"
  weight = 5
  url = "/influxdb/clients"
[[menu.influxdb]]
  name = "Administration"
  identifier = "administration"
  weight = 5
  url = "/influxdb/administration"
[[menu.influxdb]]
  name = "Tools"
  identifier = "tools"
  weight = 5
  url = "/influxdb/tools"
[[menu.influxdb]]
  name = "About the Project"
  identifier = "about"
  weight = 5
  url = "/influxdb/about"
