title = "InfluxData Documentation"
baseurl = "http://docs.influxdata.com/"

languageCode = "en-us"

[blackfriday]
  plainIdAnchors = true


SectionPagesMenu = "products"
[[menu.products]]
  name = "Telegraf"
  identifier = "telegraf"
  weight = 2
  url = "/telegraf/v0.2/"
[[menu.products]]
  name = "InfluxDB"
  identifier = "influxdb"
  weight = 1
  url = "/influxdb/v0.9/"
[[menu.products]]
  name = "Kapacitor"
  identifier = "kapacitor"
  weight = 3
  url = "/kapacitor/v0.1/"
[[menu.products]]
  name = "Chronograf"
  identifier = "chronograf"
  weight = 4
  url = "/chronograf/v0.2/"
[[menu.products]]
  name = "Hosted"
  identifier = "hosted"
  weight = 5
  url = "/hosted/"
[[menu.products]]
  name = "Enterprise"
  identifier = "enterprise"
  weight = 6
  url = "/enterprise/"
