title = "InfluxData Documentation"
baseurl = "https://docs.influxdata.com"

languageCode = "en-us"

[blackfriday]
  plainIDAnchors = true

# InfluxDB sections
[[menu.influxdb]]
  name = "Introduction"
  identifier = "introduction"
  weight = 0
  parent = "version_09"
[[menu.influxdb]]
  name = "Guides"
  identifier = "guides"
  weight = 10
  parent = "version_09"
[[menu.influxdb]]
  name = "Concepts"
  identifier = "concepts"
  weight = 20
  parent = "version_09"
[[menu.influxdb]]
  name = "Troubleshooting"
  identifier = "troubleshooting"
  weight = 30
  parent = "version_09"
[[menu.influxdb]]
  name = "Write Protocols and Plugins"
  identifier = "write_protocols"
  weight = 40
  parent = "version_09"
[[menu.influxdb]]
  name = "Query Language"
  identifier = "query_language"
  weight = 50
  parent = "version_09"
[[menu.influxdb]]
  name = "Client Libraries"
  identifier = "clients"
  weight = 60
  parent = "version_09"
[[menu.influxdb]]
  name = "Administration"
  identifier = "administration"
  weight = 70
  parent = "version_09"
[[menu.influxdb]]
  name = "Tools"
  identifier = "tools"
  weight = 80
  parent = "version_09"
[[menu.influxdb]]
  name = "About the Project"
  identifier = "about"
  weight = 90
  parent = "version_09"
[[menu.influxdb]]
  name = "InfluxDB Versions"
  identifier = "versions"
  weight = 100
  parent = "version_09"

# InfluxDB about
[[menu.influxdb]]
  name = "Release Notes/Changelog"
  identifier = "changelog"
  weight = 0
  url = "https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md"
  parent = "about"
[[menu.influxdb]]
  name = "Contributing"
  identifier = "contributing"
  weight = 10
  url = "https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md"
  parent = "about"
[[menu.influxdb]]
  name = "CLA"
  identifier = "cla"
  weight = 20
  url = "https://influxdata.com/community/cla.html"
  parent = "about"
[[menu.influxdb]]
  name = "Licenses"
  identifier = "licenses"
  weight = 30
  url = "https://github.com/influxdb/influxdb/blob/master/LICENSE"
  parent = "about"

# Chronograf versions
[[menu.chronograf]]
  name = "Version 0.3"
  identifier = "version_03"
  weight = 0
  url = "/chronograf/v0.3/"
  parent = "chronograf"
[[menu.products]]
  parent = "chronograf"

# Chronograf sections
[[menu.chronograf]]
  name = "Introduction"
  identifier = "introduction"
  weight = 0
  url = "/chronograf/introduction"
[[menu.chronograf]]
  name = "Troubleshooting"
  identifier = "troubleshooting"
  weight = 10
  url = "/chronograf/troubleshooting"

